version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=my-sql
    - PMA_USER=root
    - PMA_PASSWORD=password
    ports:
      - 3000:80